// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-t_rcPyndDKBI-uDRGW2QWU1ABs6Ncc',
    appId: '1:681278797561:android:e309bc1ef2d2c960035428',
    messagingSenderId: '681278797561',
    projectId: 'ailgi-3fd88',
    storageBucket: 'ailgi-3fd88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxkLADN_7CZAHFi03T3QBzdL_Hzq-hzg',
    appId: '1:681278797561:ios:04aeeefdad728ae1035428',
    messagingSenderId: '681278797561',
    projectId: 'ailgi-3fd88',
    storageBucket: 'ailgi-3fd88.firebasestorage.app',
    iosBundleId: 'com.example.ailgiNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxkLADN_7CZAHFi03T3QBzdL_Hzq-hzg',
    appId: '1:681278797561:ios:04aeeefdad728ae1035428',
    messagingSenderId: '681278797561',
    projectId: 'ailgi-3fd88',
    storageBucket: 'ailgi-3fd88.firebasestorage.app',
    iosBundleId: 'com.example.ailgiNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuOJ9ZgHfgdxO6XuPnnM17Hy90POcQe7M',
    appId: '1:681278797561:web:b40c282e51b98bba035428',
    messagingSenderId: '681278797561',
    projectId: 'ailgi-3fd88',
    authDomain: 'ailgi-3fd88.firebaseapp.com',
    storageBucket: 'ailgi-3fd88.firebasestorage.app',
    measurementId: 'G-P2K17T4B6K',
  );
}
